"""Export a fitted Gaussian HMM to a causal MetaTrader 5 indicator.

The MQL5 side lives in ``MQL5/Indicators/Practise``:

* ``HmmCore.mqh``       - Gaussian emissions + the two causal recursions
* ``HmmFeatures.mqh``   - MACD / Wilder-ATR engine, mirroring :mod:`.features`
* ``HmmIndicator.mqh``  - shared driver enforcing the causality contract
* ``HmmParams.mqh``     - generated by :func:`write_mqh`
* ``HMM_Filtering.mq5`` / ``HMM_CausalViterbi.mq5`` - the two indicators

Only FILTERING and CAUSAL_VITERBI are ported. SMOOTHING and full VITERBI both
rewrite already-emitted labels when new bars arrive, which repaints an
indicator and makes a backtest disagree with what was actually tradable.

Typical use::

    spec = FeatureSpec(names=(Mql5Feature.MACD_ATR, Mql5Feature.ATR_CLOSE),
                       macd_fast=18, macd_slow=40, macd_signal=11, atr_period=14)

    X = build_features(high, low, close, spec)
    model.fit(X[np.isfinite(X).all(axis=1)])          # fit on the SAME features

    params = params_from_model(model, spec, model_id="eurusd_h1_v1")
    write_mqh(params, mql5_indicators_dir / "Practise" / "HmmParams.mqh")
"""

from .exporter import StateOrder, build_params, params_from_model, params_from_mqh, params_hash, parse_mqh, write_mqh
from .features import PRICE_SCALED_FEATURES, FeatureSpec, Mql5Feature, build_features, ema, macd, true_range, wilder_atr
from .kernel import LABEL_NONE, LOG_ZERO, Mql5HmmKernel, Mql5HmmParams, Mql5InferenceMode
from .parity import ParityReport, check_parity, load_dump

__all__ = [
    "LABEL_NONE",
    "LOG_ZERO",
    "PRICE_SCALED_FEATURES",
    "FeatureSpec",
    "Mql5Feature",
    "Mql5HmmKernel",
    "Mql5HmmParams",
    "Mql5InferenceMode",
    "ParityReport",
    "StateOrder",
    "build_features",
    "build_params",
    "check_parity",
    "ema",
    "load_dump",
    "macd",
    "params_from_model",
    "params_from_mqh",
    "params_hash",
    "parse_mqh",
    "true_range",
    "wilder_atr",
    "write_mqh",
]
