"""High-impact economic news calendar — fetcher → parquet → reader.

Builds a calendar of scheduled high-impact macroeconomic events (FOMC, NFP, CPI, PPI, Retail
Sales, GDP, PCE, ECB, BoE) for use as a news mask and as the macro **event channel** (consumed
via an ``ExplicitRelease`` availability policy). The *fetcher code* is the canonical artifact: the
parquet is regenerated by running ``fetch-news-calendar`` (``build.py``). Re-running after a year
rolls forward picks up new dates automatically.

Layout
------
- ``_types.py``       — ``EventName``, ``ImpactTier``, ``Source`` enums.
- ``release_times.py``— release-time conventions per event (08:30 ET, etc.) + DST-aware UTC.
- ``fetchers/``       — one module per source; each exports ``fetch()`` returning
                        ``(release_date, event_name, source, impact_tier)``.
- ``build.py``        — orchestrator: joins fetchers, applies release times, writes parquet.
- ``reader.py``       — ``load_calendar()`` + ``is_event_window()``.

HTTP and atomic-write are shared with the rest of the pipeline (``okmich_quant_pipeline.http`` /
``._io``) rather than re-implemented here.
"""
from okmich_quant_pipeline.news_calendar._types import EventName, ImpactTier, Source
from okmich_quant_pipeline.news_calendar.reader import is_event_window, load_calendar

__all__ = ["EventName", "ImpactTier", "Source", "is_event_window", "load_calendar"]
